# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: ssa-registry
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin
      roles: USER, ADMIn
  task:
    execution:
      thread-name-prefix: ssa-registry-task
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: ssa-registry-scheduling
      pool:
        size: 2
  thymeleaf:
    mode: HTML
  output:
    ansi:
      enabled: detect

logging:
  file:
    name: target/ssa-registry.log

ribbon:
  eureka:
    enabled: true

zuul:
  sensitive-headers: Cookie,Set-Cookie
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  prefix: /services/
  strip-prefix: true
  semaphore:
    max-semaphores: 500

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: [ 'configprops', 'env', 'health', 'info', 'metrics', 'logfile', 'loggers', 'threaddump' ]
